/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import javax.swing.JLabel;
import javax.swing.JToggleButton;
import ctrl.C_Abstrait;
import ctrl.C_Menu;
import ctrl.EnumAction;
/**
 *
 * @author btssio
 */
public class V_Menu extends V_Abstraite {

    /**
     * Creates new form V_Connexion
     */
    public V_Menu(C_Abstrait ctrlAbstrait) {
        super(ctrlAbstrait);
        initComponents();
    }

    /**
     *
     */
 

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbGsb = new javax.swing.JLabel();
        btnMedicament = new javax.swing.JToggleButton();
        btnQuitter = new javax.swing.JToggleButton();
        btnRapport = new javax.swing.JToggleButton();
        btnPraticien = new javax.swing.JToggleButton();
        btnVisiteur = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        lbGsb.setText("GSB");

        btnMedicament.setText("Medicament");
        btnMedicament.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentActionPerformed(evt);
            }
        });

        btnQuitter.setText("quitter");
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });

        btnRapport.setText("Rapport");
        btnRapport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRapportActionPerformed(evt);
            }
        });

        btnPraticien.setText("Praticien");
        btnPraticien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPraticienActionPerformed(evt);
            }
        });

        btnVisiteur.setText("Visiteur");
        btnVisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisiteurActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(543, 543, 543)
                        .addComponent(btnQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lbGsb))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRapport, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMedicament, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPraticien, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVisiteur, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lbGsb, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnMedicament)
                .addGap(18, 18, 18)
                .addComponent(btnPraticien)
                .addGap(18, 18, 18)
                .addComponent(btnVisiteur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRapport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 212, Short.MAX_VALUE)
                .addComponent(btnQuitter)
                .addGap(79, 79, 79))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMedicamentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentActionPerformed
       ((C_Menu)controleur).medicament();
          
    }//GEN-LAST:event_btnMedicamentActionPerformed

    private void btnPraticienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPraticienActionPerformed
       ((C_Menu)controleur).praticien();
    }//GEN-LAST:event_btnPraticienActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
         ((C_Menu)controleur).fichierQuitter();
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnVisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisiteurActionPerformed
         ((C_Menu)controleur).visiteur();
    }//GEN-LAST:event_btnVisiteurActionPerformed

    private void btnRapportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRapportActionPerformed
         ((C_Menu)controleur).rapport();
    }//GEN-LAST:event_btnRapportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnMedicament;
    private javax.swing.JToggleButton btnPraticien;
    private javax.swing.JToggleButton btnQuitter;
    private javax.swing.JToggleButton btnRapport;
    private javax.swing.JToggleButton btnVisiteur;
    private javax.swing.JLabel lbGsb;
    // End of variables declaration//GEN-END:variables
}
